haskell/text-icu

Data/Text/ICU/Break.hsc
Data/Text/ICU/Break/Pure.hs

I avoided `CPP`-conditionals in this fix to simplify testing
With this fix, the code compiles w/ soon-to-be GHC 7.10 & base-4.8

Disambiguate `Word` (compat for GHC 7.10/base-4.8)

---

Data/Text/ICU/Collate/Internal.hs
README.markdown
cbits/text_icu.c
include/hs_text_icu.h

Some minor tweaks that ensure continued compatibility with ICU up to the current latest version, which is 55.
The only substantive change is that the reference to `ucol_equals()` - which anyway was always marked as `U_INTERNAL` and should not have been used in the first place - was removed from the C header file. But the `Eq` instance for `Collator` was already removed some time ago, so that function anyway wasn't being used.

Some minor ICU API updates

---

Data/Text/ICU.hs
Data/Text/ICU/BitMask.hs
Data/Text/ICU/Spoof.hsc
Data/Text/ICU/Spoof/Internal.hs
Data/Text/ICU/Spoof/Pure.hs
cbits/text_icu.c
include/hs_text_icu.h
tests/Properties.hs
tests/QuickCheckUtils.hs
text-icu.cabal

This is my first attempt at integrating ICU's Unicode spoof-checking library with `Data.Text.ICU`.
This library checks for nasty Unicode lookalikes:
```
λ import Data.Text
λ import Data.Text.ICU
λ areConfusable spoof (pack "Hello") (pack "World")
CheckOK
λ let cyrillic = "\x0410\x0412\x0421\x0415"
λ :print cyrillic
cyrillic = "АВСЕ"
λ areConfusable spoof (pack "ABCE") (pack cyrillic)
CheckFailed [MixedScriptConfusable,WholeScriptConfusable]
```
More tests are better, but this is a nice start.
C library: http://icu-project.org/apiref/icu4c/uspoof_8h.html

New module Data.Text.ICU.Spoof

---

text-icu.cabal

Basically because of http://stackoverflow.com/questions/7420514/using-text-icu-library-in-haskell-on-mac-os

Added paths for OS X Homebrew installation of `icu`

---

Data/Text/ICU/Break.hsc
Data/Text/ICU/Break/Pure.hs
Data/Text/ICU/Break/Types.hs
Data/Text/ICU/CaseMap.hsc
Data/Text/ICU/Char.hsc
Data/Text/ICU/Collate.hsc
Data/Text/ICU/Collate/Internal.hs
Data/Text/ICU/Convert.hs
Data/Text/ICU/Internal.hsc
Data/Text/ICU/Normalize.hsc
Data/Text/ICU/Regex.hs
Data/Text/ICU/Regex/Internal.hsc
Data/Text/ICU/Regex/Pure.hs
Data/Text/ICU/Spoof.hsc
Data/Text/ICU/Spoof/Internal.hs
Data/Text/ICU/Spoof/Pure.hs
Data/Text/ICU/Text.hs
cbits/text_icu.c
include/hs_text_icu.h
tests/Properties.hs
tests/QuickCheckUtils.hs
tests/Tests.hs
text-icu.cabal

Hi, this PR adds support for `text-2.0` (with UTF-8 internal representation) while keeping compatibility with previous `text` versions (that use UTF-16 internally).
A few more tests were added, and some old tests were improved. You could read about more details in the first commit message d9b00c6b574682f08e8be7a8d7db764bd048b881.

Support for text-2.0

---

text-icu.cabal

This seems to fix issues like https://github.com/alanz/haskell-lsp/issues/56 and https://github.com/alanz/haskell-lsp/issues/41

Include icuio lib

---

text-icu.cabal

I'm not sure why these changed, but this is the location on my m1 mac
with a standard brew installation.

Add lib/include dirs for newer homebrew

---

Data/Text/ICU/Calendar.hsc
Data/Text/ICU/DateFormatter.hsc
Data/Text/ICU/Enumerator.hsc
Data/Text/ICU/Locale.hsc
Data/Text/ICU/Normalize2.hsc
Data/Text/ICU/NumberFormatter.hsc
tests/Properties.hs
tests/QuickCheckUtils.hs
text-icu.cabal

Fix #60: restore build with GHC 7.10 - 8.8
- good bye (for a long while) to the very recent `LANGUAGE` extensions `BlockArguments` and `ImportQualifiedPost`
- import `(<>)` from `semigroups` in testsuite for GHC <= 8.2
- guard ghc-option `-Wcompat` under `impl(ghc >= 8.0)` conditional
- document supported GHC versions in `tested-with` field

Fix #60: restore build with GHC 7.10 - 8.8

---

.github/workflows/cabal-mac.yml

Re #58: CI for macOS using cabal build
Default CI, only that we need to set up the PKG_CONFIG_PATH for ICU.
CI run at: https://github.com/andreasabel/text-icu/actions/runs/1805852200

Re #58: CI for macOS using cabal build

---

README.markdown

Fix #59: Installation instructions for MSYS2 w/o stack

Fix #59: Installation instructions for MSYS2 w/o stack

---

Data/Text/ICU.hs
Data/Text/ICU/Collate.hsc
Data/Text/ICU/Collate/Pure.hs
cbits/text_icu.c
include/hs_text_icu.h
tests/Properties.hs

Hi! This PR allows creating collators from custom rules with the following functions that wrap [ucol_openRules()](https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/ucol_8h.html#a0cb1ddd81f322ed24e389f208eb35c8a) and [ucol_getRules()](https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/ucol_8h.html#a47699dcfa9c862b4011aea1927c53d4b).
- `Data.Text.ICU.Collate.openRules :: Text -> Maybe Bool -> Maybe Strength -> IO MCollator`
- `Data.Text.ICU.Collate.Pure.collatorFromRules :: Text -> Either ParseError Collator`
- Also exposed as `Data.Text.ICU.collatorFromRules`
- `Data.Text.ICU.Collate.Pure.collatorFromRulesWith :: Text -> [IO.Attribute] -> Either ParseError Collator`
- Also exposed as `Data.Text.ICU.collatorFromRules`
- `Data.Text.ICU.Collate.getRules :: MCollator -> IO …

Support for creating a collator from custom rules

---

.github/workflows/cabal-mac-win.yml
.github/workflows/haskell-ci.yml
cabal.haskell-ci
text-icu.cabal

Haskell-CI bumped to 9.4.2.
The macOS/Windows CI bumped to 9.4.1.  Once we have
- https://github.com/haskell/actions/pull/115
these could be bumped to 9.4.2 as well, but there is no point in waiting right now.

Bump CI to GHC 9.4; various other CI bumps

---

.github/workflows/cabal-mac-win.yml

This bumps the mac/win CI to the latest versions.  Closes #80.
Ran into 
- https://github.com/actions/runner-images/issues/6364 
which is fixed since 2022-10-10.  Kept code that prints useful debugging info around `pkg-config`.
The individual commits are not meaningful, need to be __SQUASHED__.

CI max/win: bump haskell/actions/setup to v2, bump GHC to 9.4.2

---

README.markdown

Different macOS architectures have different homebrew install locations, it can be either `/usr/local`  or `/opt/homebrew`.   The correct location is obtained via `brew --prefix`.

README: make PKG_CONFIG_PATH portable on macOS

---

.github/workflows/cabal-mac-win.yml
.github/workflows/haskell-ci.yml
text-icu.cabal

Bump CI to GHC 9.4.4 and 9.2.5.
Use `$(brew --prefix)` for `PKG_CONFIG_PATH`, cf:
- #84

Bump CI to GHC 9.4.4 9.2.5; use $(brew --prefix) for PKG_CONFIG_PATH

---

.github/workflows/cabal-mac-win.yml
.github/workflows/haskell-ci.yml
text-icu.cabal

Address issue of the cache action under Windows:
- https://github.com/actions/cache/issues/1073
- workaround: do not add MSYS2 /usr/bin to PATH, as it the cache action gets confused about `tar` then
- improve cache key to include ICU version
- don't use freeze file in cache key (as it contains time stamps), rather use `plan.json`
Include GHC 9.6.1 alpha2 in Haskell CI.
Some overhaul of the `.cabal` file (mostly cosmetic).
- Bump to `cabal-version: 1.18` to use `extra-doc-files` field.
- Remove redundant `-fwarn-tabs` (included in `-Wall`).
- Formatting the dependencies.
NB: Since CI does not run often here, most caches anyway get deleted (after a week) rather than reused.  
However, I want to set a good example with a good caching logic.

CI maintenance: GHC 9.6, caching under Windows

---

text-icu.cabal

Force-adding homebrew paths to `text-icu`, causes compilation and link errors on systems that have a mixture of homebrew and other system library providers. There currently is no way to prohibit `text-icu` from _not_ force-injecting homebrew paths. 
This change adds a flag to allow disabling the forced addition of homebrew paths to the package description.
Morally I'd argue that this flag should be off by default, I do however see this as a harder case to argue, and the current on-by-default to be less contentious.

Make homebrew optional

---

.github/workflows/haskell-ci.yml
cabal.haskell-ci
changelog.md
text-icu.cabal

Minimum version is now GHC 8.0 (base-4.9).
Bumped upper bound of `time` for GHC 9.10.
Removed duplicate bounds from cabal file: bounds in library need not be repeated in testsuite.
CI uses the ghcup install method now everywhere which is less flaky than apt.

Bump CI to GHC 9.10.0; drop support for GHC 7

---

.github/workflows/cabal-mac-win.yml
.github/workflows/haskell-ci.yml
.github/workflows/stack.yml
cabal.haskell-ci
text-icu.cabal

- **Bump Haskell CI to jammy distribution**
- **CI mac: drop GHC 9.0 (not supported by macos-latest)**

Bump CI to macos-14 runner

---

.github/workflows/cabal-mac-win.yml
.github/workflows/stack.yml

- **CI Cabal mac/win: cache even when build failed**
- **CI stack: add ubuntu-24.04 runner**

CI: Stack: add ubuntu-24.04; Cabal: tweak cache logic
